//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Money
    {
        public int ID { get; set; }
        public int Cost { get; set; }
        public Nullable<int> Discount_id { get; set; }
    
        public virtual Discount Discount { get; set; }
    }
}
