//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotInstagram.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hadypir_instaEntities : DbContext
    {
        public hadypir_instaEntities()
            : base("name=hadypir_instaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<Money> Moneys { get; set; }
        public virtual DbSet<TempData> TempDatas { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
